### PR TITLE
Several bugfixes for newer pandas versions

### PR DESCRIPTION
**Pull request by mgalardini**
Hi,

I already expressed how much this script is welcomed on twitter, but please let me repeat it here: thanks a lot for this.

I think that newer versions of pandas lead to some errors and exceptions. The suggested changes allowed me to run the script with either python2 or python3, with the following libraries versions:

    numpy==1.13.1
    pandas==0.20.3
    patsy==0.4.1
    pkg-resources==0.0.0
    python-dateutil==2.6.1
    pytz==2017.2
    six==1.10.0

I didn't touch any of the divisions, as I still get `3.94234179311e-05` as the maximum difference with the R version. So I assume they all are float divisions.

Please do let me know if anything is unclear or if I introduced any unwelcome change.

Best,
Marco

### CODE REVIEW

**Comment by brentp** [comment]
cheers. would you mind changing .travis.yml so that it has:
```
PATH=/home/travis/miniconda*/bin:$PATH
```
so the tests will run (I think that will do it).

**Comment by brentp** [comment]
and would you mind sqashing into a single commit?

**Comment by mgalardini** [comment]
Absolutely, will do it in the AM CET

**Comment by mgalardini** [comment]
Ended up opening a new pull request, sorry about the mix up

**Pull request closed without merging**
